import { v4 as uuidv4 } from 'uuid';

const data = [
    {
        id: uuidv4(),
        name: "Cutlery",
        price: "499",
        image: "https://ikkis.in/wp-content/uploads/2020/05/31KataChamachCutlerySet_2.jpg",
        inStock: 5,
        fastDelivery: true,
        ratings: 5,
    },
    {
        id: uuidv4(),
        name: "Braclet",
        price: "299",
        image: "https://m.media-amazon.com/images/I/61iN+KGlPjL._AC_UY1100_.jpg",
        inStock: 7,
        fastDelivery: false,
        ratings: 4,
    },
    {
        id: uuidv4(),
        name: "Door Hangings",
        price: "599",
        image: "https://m.media-amazon.com/images/I/81-WYkum6cL._AC_UF894,1000_QL80_.jpg",
        inStock: 3,
        fastDelivery: false,
        ratings: 3,
    },
    {
        id: uuidv4(),
        name: "Wall Art",
        price: "449",
        image: "https://m.media-amazon.com/images/I/71WAFpiuTBL._AC_UF894,1000_QL80_.jpg",
        inStock: 0,
        fastDelivery: true,
        ratings: 5,
    },
    {
        id: uuidv4(),
        name: "Artisanal Wooden Figurine",
        price: "799",
        image: "https://m.media-amazon.com/images/I/61WnLSDwyRL._AC_UF1000,1000_QL80_.jpg",
        inStock: 5,
        fastDelivery: false,
        ratings: 2,
    },
    {
        id: uuidv4(),
        name: "Decorative Cushion Cover",
        price: "349",
        image: "https://m.media-amazon.com/images/I/61dFUQOHfXL._AC_UF894,1000_QL80_.jpg",
        inStock: 3,
        fastDelivery: false,
        ratings: 1,
    },
    {
        id: uuidv4(),
        name: "Artist Organizer",
        price: "399",
        image: "https://images-cdn.ubuy.co.in/635bc287713dcf736b6d042c-bamboo-360-rotating-art-supply.jpg",
        inStock: 7,
        fastDelivery: true,
        ratings: 5,
    },
    {
        id: uuidv4(),
        name: "Wood Cutting Board",
        price: "1799",
        image: "https://m.media-amazon.com/images/I/81qY7GzWd4L.jpg",
        inStock: 0,
        fastDelivery: false,
        ratings: 3,
    },
    {
        id: uuidv4(),
        name: "Embroidered Hanky",
        price: "299",
        image: "https://aamori.in/image/catalog/Hankies/Red%20FloralHE%20White%20Handkerchief5%20Women%20Aamori%20Detail%202.jpg",
        inStock: 7,
        fastDelivery: true,
        ratings: 5,
    },
    {
        id: uuidv4(),
        name: "Canvas Art",
        price: "1599",
        image: "https://rukminim2.flixcart.com/image/850/1000/krkyt8w0/painting/n/7/y/12-peacock-canvas-painting-canvasstocks-original-imag5c9k75gvkr6v.jpeg?q=20",
        inStock: 3,
        fastDelivery: false,
        ratings: 3,
    },
]

export default data;